# Generated by Django 3.2.9 on 2022-03-23 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20220322_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='skill',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
