# Generated by Django 3.2.9 on 2022-03-23 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_profile_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skill',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
