# Generated by Django 3.2.9 on 2022-03-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='default-profile-image.png', null=True, upload_to='images'),
        ),
    ]
