# Generated by Django 3.2.9 on 2022-03-25 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='generation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
